//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.23 at 06:09:43 PM MSK 
//


package com.example.demosoap.model;

import javax.xml.bind.annotation.XmlRegistry;
import java.util.Collections;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the soapspringboot package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: userssoap
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EditUserRequest }
     *
     */
    public EditUserRequest createEditUserRequest() {
        return new EditUserRequest();
    }

    /**
     * Create an instance of {@link User }
     *
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link GetUserResponse }
     *
     */
    public GetUserResponse createGetUserResponse() {
        return new GetUserResponse();
    }

    /**
     * Create an instance of {@link OperationResponse }
     *
     */
    public OperationResponse createOperationResponse() {
        return new OperationResponse();
    }

    /**
     * Create an instance of {@link GetUserRequest }
     *
     */
    public GetUserRequest createGetUserRequest() {
        return new GetUserRequest();
    }

    /**
     * Create an instance of {@link CreateNewUserRequest }
     *
     */
    public CreateNewUserRequest createCreateNewUserRequest() {
        return new CreateNewUserRequest();
    }

    /**
     * Create an instance of {@link RemoveUserRequest }
     *
     */
    public RemoveUserRequest createRemoveUserRequest() {
        return new RemoveUserRequest();
    }

    /**
     * Create an instance of {@link GetUsersResponse }
     *
     */
    public GetUsersResponse createGetUsersResponse() {
        return new GetUsersResponse();
    }

    /**
     * Create an instance of {@link UserDto }
     *
     */
    public UserDto createUserDto() {
        return new UserDto();
    }

    /**
     * Create an instance of {@link Role }
     *
     */
    public Role createRole() {
        return new Role();
    }


}
